

services:
  backend:
    build: ./server
    container_name: ecommerce_backend
    ports: 
      - "3001:3001"
    env_file:
      - ./server/.env
    environment:
     NODE_ENV: production
     REDIS_URL: ecommerce_redis
    depends_on:
      - redis

  frontend:
    build: ./client
    container_name: ecommerce_frontend
    ports:
      - "80:80"
    environment:
    - VITE_API_URL=http://ecommerce_backend:3001
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    container_name: ecommerce_redis
    ports:
      - "6379:6379"